#!/bin/bash

set -e

echo "========================================="
echo " QUALITI - BETA RELEASE PREPARATION"
echo "========================================="

DATE=$(date +"%Y%m%d_%H%M%S")

CURRENT_DIR=$(pwd)

ARCHIVE_DIR="../qualiti-archive-$DATE"
RELEASE_DIR="../qualiti-release"

echo ""
echo "[1/12] Criando backup completo..."

cp -R "$CURRENT_DIR" "$ARCHIVE_DIR" 2>/dev/null || true

echo "Backup criado:"
echo "$ARCHIVE_DIR"

echo ""
echo "[2/12] Criando tag de segurança..."

git tag "pre-release-cleanup-$DATE" || true

echo ""
echo "[3/12] Criando estrutura INTERNAL..."

mkdir -p internal/reports
mkdir -p internal/recovery
mkdir -p internal/audits
mkdir -p internal/execution

echo ""
echo "[4/12] Movendo artefatos internos..."

find . -iname "*walkthrough*" -exec mv {} internal/execution/ \; 2>/dev/null || true
find . -iname "*task*" -exec mv {} internal/execution/ \; 2>/dev/null || true

find . -iname "*report*" -exec mv {} internal/reports/ \; 2>/dev/null || true
find . -iname "*recovery*" -exec mv {} internal/recovery/ \; 2>/dev/null || true

find . -iname "*night_execution*" -exec mv {} internal/execution/ \; 2>/dev/null || true
find . -iname "*.patch" -exec mv {} internal/recovery/ \; 2>/dev/null || true

echo ""
echo "[5/12] Procurando referências de desenvolvimento..."

grep -RniE \
"jules|antigravity|chatgpt|openai|gpt|claude|gemini|copilot|generated by ai|autonomous execution|night execution" \
. \
--exclude-dir=node_modules \
--exclude-dir=.git \
> ai_reference_audit.txt || true

echo "Relatório:"
echo "ai_reference_audit.txt"

echo ""
echo "[6/12] Gerando Release Manifest..."

cat > release-repository-manifest.md <<EOF
# Release Repository Manifest

## CORE

app/backend
app/frontend
docker
infra

README.md
LICENSE
CHANGELOG.md

docs/adr
docs/architecture
docs/security
docs/compliance
docs/product
docs/roadmap

## INTERNAL

internal/

## REMOVE

patches
temporary scripts
debug scripts
recovery packages
execution reports
EOF

echo ""
echo "[7/12] Criando novo repositório limpo..."

rm -rf "$RELEASE_DIR"

mkdir -p "$RELEASE_DIR"

echo ""
echo "[8/12] Copiando somente arquivos essenciais..."

cp -R app "$RELEASE_DIR/" 2>/dev/null || true

cp -R docker "$RELEASE_DIR/" 2>/dev/null || true
cp -R infra "$RELEASE_DIR/" 2>/dev/null || true
cp docker-compose.yml "$RELEASE_DIR/" 2>/dev/null || true
cp Caddyfile "$RELEASE_DIR/" 2>/dev/null || true
cp .env.example "$RELEASE_DIR/" 2>/dev/null || true
cp .gitignore "$RELEASE_DIR/" 2>/dev/null || true

cp README.md "$RELEASE_DIR/" 2>/dev/null || true
cp LICENSE "$RELEASE_DIR/" 2>/dev/null || true
cp CHANGELOG.md "$RELEASE_DIR/" 2>/dev/null || true

mkdir -p "$RELEASE_DIR/docs"

cp -R docs/adr "$RELEASE_DIR/docs/" 2>/dev/null || true
cp -R docs/architecture "$RELEASE_DIR/docs/" 2>/dev/null || true
cp -R docs/security "$RELEASE_DIR/docs/" 2>/dev/null || true
cp -R docs/compliance "$RELEASE_DIR/docs/" 2>/dev/null || true
cp -R docs/product "$RELEASE_DIR/docs/" 2>/dev/null || true
cp -R docs/roadmap "$RELEASE_DIR/docs/" 2>/dev/null || true

echo ""
echo "[9/12] Inicializando Git limpo..."

cd "$RELEASE_DIR"

rm -rf .git

git init

git checkout -b main

git add .

git commit -m "release(beta): initial clean beta release"

echo ""
echo "[10/12] Criando branch beta..."

git checkout -b beta/v1

echo ""
echo "[11/12] Gerando relatório final..."

cat > release-readiness-report.md <<EOF
# Qualiti Beta Release Report

Generated: $DATE

Status:
READY FOR BETA

Checklist:

[x] Backup criado
[x] Artefatos internos removidos da release
[x] Manifesto gerado
[x] Repositório limpo criado
[x] Git inicializado
[x] Branch beta criada

Próximos passos:

1. Revisar ai_reference_audit.txt
2. Revisar documentação
3. Configurar GitHub
4. Publicar beta/v1
5. Subir ambiente beta
EOF

echo ""
echo "[12/12] Finalizado"

echo ""
echo "========================================="
echo " RELEASE BETA PREPARADA"
echo "========================================="
echo ""
echo "Novo repositório:"
echo "$RELEASE_DIR"
echo ""
echo "Próximos passos:"
echo "1. Revisar ai_reference_audit.txt"
echo "2. Revisar release-readiness-report.md"
echo "3. Criar GitHub novo"
echo "4. git remote add origin <NOVO_REPO>"
echo "5. git push -u origin beta/v1"
echo ""
